column reindexing using .loc deprecated
This fix prevents the following error:

KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Index(['MEAN_INTENSITY', 'ESTIMATED_DIAMETER', 'MEDIAN_INTENSITY',\n       'MIN_INTENSITY', 'MAX_INTENSITY', 'TOTAL_INTENSITY',\n       'STANDARD_DEVIATION', 'CONTRAST', 'SNR'],\n      dtype='object'). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"

See also: https://stackoverflow.com/questions/61291741/passing-list-likes-to-loc-or-with-any-missing-labels-is-no-longer-supported